# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI_PROD: mongodb://user:password@mongo:27017/survey-app?authSource=admin
      PORT: 5000
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost", "-u", "user", "-p", "password", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
