name: E2E Tests

on:
  push:
    # branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run E2E Tests with Docker Compose
        run: docker compose -f docker-compose.e2e.yml up --build --abort-on-container-exit e2e

      - name: Tear down Docker containers
        if: always()
        run: docker compose -f docker-compose.e2e.yml down -v