name: Linting

on:
  push:
  pull_request: 


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        working-directory: ./survey-app-frontend
        run: npm install
      - name: Check Frontend Style
        working-directory: ./survey-app-frontend
        run: npm run lint
      - name: Install Backend Dependencies
        working-directory: ./survey-app-backend
        run: npm install
      - name: Check Frontend Style
        working-directory: ./survey-app-backend
        run: npm run lint